# Python on Linux Web App
# Build a Python project (using Django/Flask/Bottle frameworks) and deploy it to Azure as a Linux web app.

# name: Build and deploy Python app to Azure Web App - sebela-ar
# on:
#   push:
#     branches: [main]

# # CONFIGURATION
# # For help, go to https://github.com/Azure/Actions
# # See this in-depth article on CI for Python applications: https://azure.github.io/AppService/2020/12/11/cicd-for-python-apps.html
# #
# # 1. Set up the following secrets in your repository:
# #   AZURE_CREDENTIALS_GITHUB_SECRET
# #
# # 2. Change these variables for your configuration:
# env:
#   AZURE_WEBAPP_NAME: sebela-ar # set this to your application's name
#   WORKING_DIRECTORY: '.'         # set this to the path to your path of working directory inside github repository, defaults to the repository root
#   PYTHON_VERSION: '3.8' 
#   STARTUP_COMMAND: ''           # set this to the startup command required to start the gunicorn server. default it is empty

# # name: Build and deploy Python app
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     # environment: dev

#     steps:
#     # checkout the repo 
#     - uses: actions/checkout@v2
    
#     # setup python
#     - name: Setup Python
#       uses: actions/setup-python@v1
#       with:
#         python-version: ${{ env.PYTHON_VERSION }}

#     - name: Create and start virtual environment
#       run: |
#         python -m venv venv
#         source venv/bin/activate
    
#     # install dependencies
#     - name: Install Dependencies
#       working-directory: ${{ env.WORKING_DIRECTORY }}
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt

#     - name: Upload artifact for deployment jobs
#       uses: actions/upload-artifact@v2
#       with:
#         name: python-app
#         path: |
#           . 
#           !venv/


#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'Production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#     steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v2
#         with:
#           name: python-app
#           path: .
      
#       # deploy web app
#       - name: 'Deploy to Azure Web App'
#         uses: azure/webapps-deploy@v2
#         id: deploy-to-webapp
#         with:
#           # app-name: ${{ env.AZURE_WEBAPP_NAME }}
#           # slot-name: 'Production'
#           # publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BACD3A57D7464D6BB71F04A251E2D800 }}
#           app-name: ${{ env.AZURE_WEBAPP_NAME }}
#           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#           package: ${{ env.WORKING_DIRECTORY }}
#           startup-command: ${{ env.STARTUP_COMMAND }}

      






# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - sebela-ar

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'sebela-ar'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BACD3A57D7464D6BB71F04A251E2D800 }}

